#!/bin/bash
if [ $# -ne 2 ]
then
  echo "Expecting 2 args, username and password for the smtp account"
  exit 1
fi

username=$1
password=$2

echo "dc_eximconfig_configtype='smarthost'
dc_other_hostnames="$(hostname)"
dc_local_interfaces='127.0.0.1 ; ::1'
dc_readhost='da'
dc_relay_domains=''
dc_minimaldns='false'
dc_relay_nets=''
dc_smarthost='smtp.sendgrid.net:587'
CFILEMODE='644'
dc_use_split_config='true'
dc_hide_mailname='false'
dc_mailname_in_oh='true'
dc_localdelivery='mail_spool'" | sudo tee /etc/exim4/update-exim4.conf.conf > /dev/null

echo "smtp.sendgrid.net:$username:$password" | sudo tee /etc/exim4/passwd.client > /dev/null

cp disk_alert /etc/cron.daily/
chmod +x /etc/cron.daily/disk_alert
